"""Add code fields

Revision ID: f5ba482e6677
Revises: 
Create Date: 2025-05-06 12:59:50.982635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ba482e6677'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('generated_code', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('associated_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'associated_code')
    op.drop_column('jobs', 'generated_code')
    # ### end Alembic commands ###
